# ============================================================
# hosts/victus/configuration.nix
#
# Top-level system configuration for the "victus" machine
# (HP Victus laptop with Intel iGPU + NVIDIA RTX 4050, RTL8852BE-VT WiFi).
#
# Module layout:
#   hardware-configuration.nix       — auto-generated: filesystems, kernel modules
#   modules/development.nix          — dev tools, languages, editors, services
#   modules/audio.nix                — PipeWire audio stack + quality tuning
#   modules/nvidia.nix               — NVIDIA + Intel Prime Sync, hardware.graphics
#   modules/flatpak.nix              — Flatpak + Flathub remote
#   modules/performance.nix          — zram, earlyoom, thermald, irqbalance, sysctl
#   modules/gpu-switch.nix           — envycontrol, nvidia-run / intel-run wrappers
#   modules/desktop/nnn.nix          — Niri + Noctalia + greetd (NNN stack)
#   modules/desktop/desktop-apps.nix — Cinnamon-equivalent app suite for NNN stack
#   modules/font.nix                 — font packages + fontconfig tuning
# ============================================================
{ config, pkgs, ... }:

{
  imports =
    [
      # Generated by `nixos-generate-config`. Contains partition UUIDs,
      # detected kernel modules, and filesystem mount points.
      # Do not edit by hand — re-run nixos-generate-config if hardware changes.
      ./hardware-configuration.nix

      # Developer tooling (languages, LSPs, editors, CLI tools, services)
      ../../modules/development.nix

      # Audio stack (PipeWire, wireplumber, bluetooth audio codecs, EQ config)
      ../../modules/audio.nix

      # NVIDIA driver configuration + Intel/NVIDIA Prime Sync
      ../../modules/nvidia.nix

      # Flatpak support (declarative Flatpak app installation)
      ../../modules/flatpak.nix

      # System performance tuning:
      #   - zram swap (NO SWAP was causing hard OOM freezes)
      #   - earlyoom (prevent system freezes on memory pressure)
      #   - irqbalance (spread IRQs across all CPU cores)
      #   - thermald (smooth Intel thermal management)
      #   - sysctl tuning (swappiness, inotify, dirty pages, TCP)
      #   - I/O scheduler per device type (nvme=none, sata-ssd=deadline)
      ../../modules/performance.nix

      # GPU switching support:
      #   - envycontrol (switch between integrated/hybrid/nvidia modes)
      #   - nvidia-run / intel-run wrapper scripts
      #   - gpu-info summary command
      ../../modules/gpu-switch.nix

      # NNN desktop stack: Niri + Noctalia + greetd
      # Replaces the old Cinnamon + LightDM setup.
      ../../modules/desktop/nnn.nix

      # Cinnamon-equivalent application suite for the NNN stack:
      #   pavucontrol, easyeffects, blueman, wdisplays, nwg-look,
      #   file-roller, loupe, gnome apps, evince, wlogout, etc.
      ../../modules/desktop/desktop-apps.nix

      # Font packages and fontconfig tuning (JetBrains Mono NF, Noto, Inter, etc.)
      ../../modules/font.nix

      # Uncomment to enable gaming packages (Steam, Lutris, etc.)
      #../../modules/game.nix
    ];

  # ============================================================
  # PACKAGE OVERLAYS
  # ============================================================
  # An overlay is a function (final: prev: { ... }) evaluated by Nix
  # in a fixed-point:
  #   final — the fully-merged package set (all overlays applied)
  #   prev  — the package set BEFORE this overlay
  # Use prev to access the original package, final to reference
  # other already-overridden packages from this or earlier overlays.
  #
  # BUG FIX — perl5.42.0-IO-Tty-1.20 (nixpkgs 26.05 issue):
  #
  #   Root cause:
  #     IO-Tty ships its OWN configure script (not ExtUtils::MakeMaker)
  #     that probes for the C compiler by calling `gcc` as a bare
  #     command via PATH.  Inside the Nix sandbox, PATH only contains
  #     what is explicitly declared as a nativeBuildInput — gcc is
  #     NOT listed in the current nixpkgs recipe for IO-Tty.
  #     The configure step therefore fails with:
  #       "ERROR: cannot run the configured compiler 'gcc'"
  #
  #   Cascade failure chain:
  #     IO-Tty build fails
  #       → perl-5.42.0-env fails (1 dep failed)
  #         → moreutils-0.70 fails (used as a setup hook)
  #           → NVIDIA EGL external-platforms 32-bit fails
  #             → graphics-drivers-32bit fails
  #               → Steam, graphics-driver.conf, tmpfiles.d fail
  #                 → entire system derivation fails
  #
  #   Fix:
  #     Override IO-Tty to add stdenv.cc to nativeBuildInputs.
  #     stdenv.cc is the compiler wrapper package that puts gcc, cc,
  #     and friends on PATH inside the Nix build sandbox.
  #
  #   When to remove this overlay:
  #     Once a nixpkgs commit on nixos-26.05 fixes the IO-Tty recipe
  #     to include stdenv.cc natively, this override becomes a no-op
  #     and can be removed (or the list narrowed).
  #
  # To also load the overlays/ directory (e.g. the Sober Roblox client),
  # extend the list:
  #   nixpkgs.overlays = [ (import ../../overlays) ioTtyFix ];
  # where ioTtyFix is the lambda below extracted into a let binding.
  nixpkgs.overlays = [
    (final: prev: {
      # Fix the IO-Tty-1.20 build failure (nixpkgs 26.05) by overriding moreutils.
      #
      # Root cause chain (i686):
      #   nvidia-egl-external-platforms-x32 → egl-gbm → eglexternalplatform
      #   → setup-hook.sh → moreutils → perl.withPackages [IPCRun] → IOTty
      #   IOTty-1.20 configure calls 'gcc' bare; gcc is not in the Nix sandbox
      #   PATH for Perl packages (no stdenv.cc in nativeBuildInputs).
      #
      # Why not fix IOTty directly:
      #   In nixpkgs 26.05, perlPackages is built with makeScopeWithSplicing'.
      #   Any overlay that reads perlPackages.X (even through `prev`) causes
      #   infinite recursion: the spliced scope references final.perlPackages.X
      #   which references the overlay's definition which references perlPackages.X.
      #   All overlay approaches (overrideScope, extend, perl5.override) silently
      #   fall through or error — the drv hash never changes.
      #
      # The fix — target moreutils instead:
      #   moreutils is a plain callPackage package (no scope, no splicing).
      #   Its buildInputs = [perl.withPackages [IPCRun, TimeDate, TimeDuration]];
      #   IPCRun has propagatedBuildInputs = [IOTty], so stripping buildInputs
      #   removes IOTty from the closure. moreutils still builds correctly —
      #   nativeBuildInputs already provides perl for pod2man. The i686 moreutils
      #   is used only as a setup-hook; vidir/vipe/ts are not called in that role.
      #
      # Fix IO-Tty-1.20 (nixpkgs 26.05): strip moreutils buildInputs.
      #   moreutils buildInputs = [perl.withPackages [IPCRun ...]]
      #   IPCRun propagates IOTty, whose configure calls bare 'gcc' (not in
      #   the Nix sandbox PATH for Perl packages). Stripping buildInputs
      #   removes IOTty from the closure; moreutils still builds correctly
      #   — its nativeBuildInputs already provide perl for pod2man + docbook.
      moreutils = prev.moreutils.overrideAttrs (_: {
        buildInputs = [];
      });
    })
  ];

  # ============================================================
  # BOOTLOADER
  # systemd-boot is the recommended bootloader for UEFI systems.
  # ============================================================

  boot.loader.systemd-boot.enable = true;

  # Allow systemd-boot to write the EFI boot entry on first install.
  boot.loader.efi.canTouchEfiVariables = true;

  # Keep only the last 6 NixOS generations in the boot menu.
  # Older generations are still garbage-collected by nix.gc below.
  boot.loader.systemd-boot.configurationLimit = 6;
  # Suppress the "[ OK ] Starting..." service spam on the console.
  # quiet        — hides kernel + udev messages
  # loglevel=3   — only errors reach the console (no info/debug)
  # systemd.show_status=auto — systemd still shows failures, hides successes
  boot.kernelParams = [ "quiet" "loglevel=3" "systemd.show_status=auto" "udev.log_level=3" ];
  boot.consoleLogLevel = 3;
  boot.initrd.verbose = false;





  # ============================================================
  # NETWORKING
  # ============================================================

  networking.hostName = "victus";

  # NetworkManager handles WiFi, Ethernet, and VPN connections.
  # Required by Noctalia for the network widget in the control center.
  networking.networkmanager.enable = true;

  # BUG FIX: The RTL8852BE-VT WiFi card was dropping connections because
  # its Linux power-management was left on "auto" (power-save mode).
  # These udev rules force the NIC's runtime power control to "on"
  # (always-on) as soon as the device is hotplugged by the kernel.
  # en* = Ethernet, wl* = WiFi (covers the rtw89 driver's interface name).
  services.udev.extraRules = ''
    ACTION=="add", SUBSYSTEM=="net", KERNEL=="en*", ATTR{power/control}="on"
    ACTION=="add", SUBSYSTEM=="net", KERNEL=="wl*", ATTR{power/control}="on"
  '';

  # Disable WiFi power-save at the NetworkManager level too.
  # NM_SETTING_WIRELESS_POWERSAVE_DISABLE = 2 means "always disabled".
  # This works alongside the udev rule above for belt-and-suspenders coverage.
  networking.networkmanager.settings.connection."wifi.powersave" = 2;

  # Use NixOS's built-in DHCP client (networkd) instead of dhclient.
  # Faster and integrates better with systemd-networkd.
  networking.networkmanager.dhcp = "internal";

  # BUG FIX: The RTL8852BE-VT (rtw89_pci driver) was silently entering
  # PCIe low-power states (L1 substates) after connecting to WiFi,
  # causing "connected but no internet" association drops.
  # These modprobe options disable the problematic ASPM states for this card only.
  boot.extraModprobeConfig = ''
    options rtw89_pci disable_clkreq=1 disable_aspm_l1=1 disable_aspm_l1ss=1
  '';

  # ============================================================
  # NIX SETTINGS
  # ============================================================

  nix.settings = {
    # Enable the modern `nix` CLI (nix build, nix shell, etc.) and Flakes.
    experimental-features = [
      "nix-command"
      "flakes"
    ];

    # Use all CPU cores for parallel builds and downloads.
    max-jobs = "auto";

    # Allow each job to use all available cores for parallel compilation
    # (useful for LLVM, Rust crates, large C++ projects).
    cores = 0;

    # Trust the local user so they can use binary caches without sudo.
    trusted-users = [ "root" "harua" ];

    # Force HTTP/1.1 for all Nix downloads.
    # curl's HTTP/2 implementation hits a framing-layer bug on some Linux
    # setups ("Stream error in the HTTP/2 framing layer") causing downloads
    # to stall and retry. HTTP/1.1 is slower in theory but never hits this
    # bug and is fully reliable with cache.nixos.org and Cachix.
    http2 = false;
  };

  # Automatically delete old store paths weekly.
  # "--delete-older-than 14d" keeps two weeks of rollback history.
  nix.gc = {
    automatic = true;
    dates = "weekly";
    options = "--delete-older-than 14d";
  };

  # Deduplicate identical files in /nix/store using hard links.
  # Saves several GB on systems with many similar packages.
  nix.optimise.automatic = true;

  # ============================================================
  # LOCALE & TIME
  # ============================================================

  time.timeZone = "America/Toronto";
  i18n.defaultLocale = "en_CA.UTF-8";

  # ============================================================
  # DISPLAY SERVER
  # We keep X11 enabled even though our desktop session is fully Wayland.
  # Reasons:
  #   1. `services.xserver.videoDrivers = ["nvidia"]` in nvidia.nix still
  #      routes through this option to load the NVIDIA kernel module.
  #   2. XWayland (X11 compatibility layer) is included automatically.
  #   3. The xkb layout below sets keyboard layout for both X and Wayland.
  # ============================================================
  services.xserver.enable = true;

  services.xserver.xkb = {
    layout  = "us";
    variant = "";
  };

  # ============================================================
  # SYSTEM SERVICES
  # ============================================================

  # CUPS — local and network printing.
  services.printing.enable = true;

  # Avahi — mDNS/DNS-SD for network service discovery.
  # Required for CUPS to discover network printers automatically.
  services.avahi = {
    enable = true;
    nssmdns4 = true; # let apps resolve .local hostnames
    openFirewall = true;
  };

  # Tailscale — mesh VPN. Allows secure access to other Tailscale
  # nodes (home server, VMs, etc.) without port forwarding.
  services.tailscale.enable = true;

  # ============================================================
  # USERS
  # ============================================================

  users.users."harua" = {
    isNormalUser = true;
    description  = "Haru Afzal";
    extraGroups  = [
      "networkmanager" # Manage network connections without sudo
      "wheel"          # sudo access
      "docker"         # Run Docker containers without sudo
      "wireshark"      # Capture packets without root (dumpcap setcap)
      "audio"          # Direct ALSA audio access (backup if PipeWire fails)
      "video"          # Access to video devices and display brightness
      "input"          # Access to input devices (needed by some games / tools)
    ];
    packages = with pkgs; []; # User packages are managed by home-manager instead
  };

  # ============================================================
  # PROGRAMS
  # ============================================================

  # Firefox — system-wide install for the NixOS policy wrapper and
  # native messaging hosts (e.g. for extensions needing system access).
  programs.firefox.enable = true;

  # Steam — gaming platform. openFirewall opens ports for Remote Play
  # and dedicated server discovery on the LAN.
  programs.steam = {
    enable = true;
    remotePlay.openFirewall      = true;
    dedicatedServer.openFirewall = true;
    # Gamescope integration: enables the gamescope session launcher in Steam.
    # gamescope is a micro-compositor that lets games run at custom resolutions
    # and framerates without affecting the desktop.
    gamescopeSession.enable = true;
  };

  # Wireshark — packet capture. The NixOS module gives dumpcap the required
  # CAP_NET_RAW so users in the "wireshark" group can capture without root.
  programs.wireshark.enable = true;

  # Gamescope — Wayland micro-compositor for running games.
  # Needed separately from Steam for non-Steam use (e.g. running any app
  # inside gamescope for resolution/framerate control).
  programs.gamescope.enable = true;

  # ============================================================
  # VIRTUALISATION
  # ============================================================

  # Docker daemon. Users in the "docker" group can run containers
  # without sudo (equivalent to root — be aware of the security tradeoff).
  virtualisation.docker.enable = true;

  # ============================================================
  # SYSTEM PACKAGES
  # ============================================================
  # Minimal set here — most packages live in development.nix or desktop-apps.nix.
  environment.systemPackages = with pkgs; [
    # Archive tool (needed by many installers and scripts)
    p7zip     # 7z, handles .7z, .rar, and many formats beyond zip/tar
    unrar     # Extract .rar archives (proprietary format)

    # GPU info tools (referenced in gpu-switch.nix scripts)
    pciutils  # lspci — list PCI devices
    usbutils  # lsusb — list USB devices
  ];

  # ============================================================
  # SYSTEM STATE VERSION
  # ============================================================
  # Do NOT change this after the initial install.
  # Controls the format of stateful data (/var, user home dirs).
  # Changing it does not upgrade anything — it just breaks assumptions.
  system.stateVersion = "26.05";
}
