# ============================================================
# hosts/victus/configuration.nix
#
# Top-level system configuration for the "victus" machine
# (HP Victus laptop with Intel iGPU + NVIDIA RTX 4050, RTL8852BE-VT WiFi).
#
# Module layout:
#   hardware-configuration.nix  — auto-generated: filesystems, kernel modules
#   modules/development.nix     — dev tools, languages, editors
#   modules/audio.nix           — PipeWire / sound setup
#   modules/nvidia.nix          — NVIDIA + Intel Prime Sync, hardware.graphics
#   modules/flatpak.nix         — Flatpak + Flathub remote
#   modules/desktop/nnn.nix     — Niri + Noctalia + greetd (NNN stack)
# ============================================================
{ config, pkgs, ... }:

{
  imports =
    [
      # Generated by `nixos-generate-config`. Contains partition UUIDs,
      # detected kernel modules, and filesystem mount points.
      # Do not edit by hand — re-run nixos-generate-config if hardware changes.
      ./hardware-configuration.nix

      # Developer tooling (languages, LSPs, editors, etc.)
      ../../modules/development.nix

      # Audio stack (PipeWire, wireplumber, bluetooth audio codecs)
      ../../modules/audio.nix

      # NVIDIA driver configuration + Intel/NVIDIA Prime Sync
      ../../modules/nvidia.nix

      # Flatpak support (declarative Flatpak app installation)
      ../../modules/flatpak.nix

      # NNN desktop stack: Niri + Noctalia + greetd
      # This replaces the old Cinnamon + LightDM setup.
      ../../modules/desktop/nnn.nix

      # Uncomment to enable gaming packages (Steam, Lutris, etc.)
      #../../modules/game.nix

      # Font packages and fontconfig tuning (JetBrains Mono NF, Noto, Inter, etc.)
      ../../modules/font.nix
    ];

  # Overlays let you patch or replace packages from nixpkgs.
  # Uncomment if you have custom overlays in the overlays/ directory.
  #nixpkgs.overlays = [ (import ../../overlays) ];

  # ============================================================
  # BOOTLOADER
  # systemd-boot is the recommended bootloader for UEFI systems.
  # ============================================================

  boot.loader.systemd-boot.enable = true;

  # Allow systemd-boot to write the EFI boot entry on first install.
  boot.loader.efi.canTouchEfiVariables = true;

  # Keep only the last 6 NixOS generations in the boot menu.
  # Older generations are still garbage-collected separately by nix.gc below.
  boot.loader.systemd-boot.configurationLimit = 6;

  # ============================================================
  # NETWORKING
  # ============================================================

  networking.hostName = "victus";

  # NetworkManager handles WiFi, Ethernet, and VPN connections.
  # Required by Noctalia for the network widget in the control center.
  networking.networkmanager.enable = true;

  # BUG FIX: The RTL8852BE-VT WiFi card was dropping connections because
  # its Linux power-management was left on "auto" (power-save mode).
  # These udev rules force the NIC's runtime power control to "on"
  # (always-on) as soon as the device is hotplugged by the kernel.
  # en* = Ethernet, wl* = WiFi (covers the rtw89 driver's interface name).
  services.udev.extraRules = ''
    ACTION=="add", SUBSYSTEM=="net", KERNEL=="en*", ATTR{power/control}="on"
    ACTION=="add", SUBSYSTEM=="net", KERNEL=="wl*", ATTR{power/control}="on"
  '';

  # Disable WiFi power-save at the NetworkManager level too.
  # NM_SETTING_WIRELESS_POWERSAVE_DISABLE = 2 means "always disabled".
  # This works alongside the udev rule above for belt-and-suspenders coverage.
  # extraConfig was removed in 26.05; we use structured settings now.
  networking.networkmanager.settings.connection."wifi.powersave" = 2;

  # Use NixOS's built-in DHCP client (networkd) instead of the external
  # dhclient binary. Faster and integrates better with systemd-networkd.
  networking.networkmanager.dhcp = "internal";

  # BUG FIX: The RTL8852BE-VT (rtw89_pci driver) was silently entering
  # PCIe low-power states (L1 substates) after connecting to WiFi,
  # causing the card to lose association with the AP ("connected but no internet").
  # These modprobe options disable the problematic ASPM states for this card only.
  boot.extraModprobeConfig = ''
    options rtw89_pci disable_clkreq=1 disable_aspm_l1=1 disable_aspm_l1ss=1
  '';

  # ============================================================
  # NIX SETTINGS
  # ============================================================

  # Enable the modern `nix` CLI (nix build, nix shell, etc.)
  # and Flakes support. Both are still experimental but stable
  # enough to be required by this configuration.
  nix.settings = {
    experimental-features = [
      "nix-command"
      "flakes"
    ];

    # Use all CPU cores for parallel builds and downloads.
    # "auto" = one job per logical CPU core.
    max-jobs = "auto";

    # Allow each job to use all available cores (for packages that
    # support parallel compilation, e.g. LLVM, Rust crates).
    cores = 0;
  };

  # Automatically delete old store paths weekly.
  # "--delete-older-than 14d" keeps two weeks of rollback history.
  nix.gc = {
    automatic = true;
    dates = "weekly";
    options = "--delete-older-than 14d";
  };

  # Deduplicate identical files in /nix/store using hard links.
  # Saves several GB on systems with many similar packages (e.g. dev shells).
  nix.optimise.automatic = true;

  # ============================================================
  # LOCALE & TIME
  # ============================================================

  time.timeZone = "America/Toronto";

  # en_CA.UTF-8 = Canadian English with UTF-8 encoding.
  i18n.defaultLocale = "en_CA.UTF-8";

  # ============================================================
  # DISPLAY SERVER
  # We keep X11 enabled even though our desktop session is now
  # fully Wayland (Niri). Reasons:
  #   1. `services.xserver.videoDrivers = ["nvidia"]` in nvidia.nix
  #      still routes through this option to load the nvidia kernel
  #      module and configure DRM.
  #   2. XWayland (X11 compatibility layer inside Niri) is included
  #      automatically; some apps still need it.
  #   3. The xkb layout below sets keyboard layout for both X and
  #      Wayland sessions.
  # The old `displayManager.lightdm` and `desktopManager.cinnamon`
  # lines have been removed — greetd + Niri replace them (see nnn.nix).
  # ============================================================
  services.xserver.enable = true;

  services.xserver.xkb = {
    layout = "us";
    variant = ""; # Default US layout, no variant
  };

  # ============================================================
  # SYSTEM SERVICES
  # ============================================================

  # Enable CUPS for local and network printing support.
  services.printing.enable = true;

  # Tailscale — mesh VPN. Allows secure access to other Tailscale
  # nodes (home server, VMs, etc.) without port forwarding.
  services.tailscale.enable = true;

  # ============================================================
  # USERS
  # ============================================================

  users.users."harua" = {
    isNormalUser = true;
    description = "Haru Afzal";
    extraGroups = [
      "networkmanager" # Manage network connections without sudo
      "wheel"          # sudo access
      "docker"         # Run Docker without sudo
      "wireshark"      # Capture packets without root (dumpcap setcap)
    ];
    packages = with pkgs; []; # User packages are managed by home-manager instead
  };

  # ============================================================
  # PROGRAMS
  # ============================================================

  # Firefox — installed system-wide so it gets the NixOS policy wrapper
  # and native messaging hosts (e.g. for extensions that need system access).
  programs.firefox.enable = true;

  # Steam — the gaming platform. openFirewall opens the ports Steam needs
  # for Remote Play and dedicated server discovery on the LAN.
  programs.steam = {
    enable = true;
    remotePlay.openFirewall = true;      # Remote Play streaming ports
    dedicatedServer.openFirewall = true; # Dedicated server discovery ports
  };

  # Wireshark — packet capture tool. The NixOS module gives the dumpcap
  # binary the required CAP_NET_RAW capability so users in the "wireshark"
  # group can capture without being root.
  programs.wireshark.enable = true;

  # ============================================================
  # VIRTUALISATION
  # ============================================================

  # Docker daemon. Users in the "docker" group can run containers
  # without sudo (equivalent to root — be aware of the security tradeoff).
  virtualisation.docker.enable = true;

  # ============================================================
  # NVIDIA — see modules/nvidia.nix for full driver config
  # ============================================================

  # The NixOS state version. Do NOT change this after the initial install.
  # It controls the format of stateful data (e.g. /var, user home dirs).
  # Changing it does not upgrade anything — it just breaks assumptions.
  system.stateVersion = "26.05";
}
